services:
  employee.api:
    image: employee.api
    build:
      context: .
      dockerfile: Employee.Api/Dockerfile
  
  postgres:
    image: postgres:latest
    container_name: employee_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5430:5432"
